### ISSUE TITLE
Enable linting for python code

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#407]
### Overview

As a developer, we should make sure that our code is maintainable. For this ticket, let's start a discussion on whether linting python code is desirable.

### Action Items

- [x] Discuss with the team on whether adding a python linter is desirable.
- [ ] Enable the python linter for super-linter if needed.

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

This has never been up for consideration previously, since vscode did not have native support for python linting, meaning that we needed to download them as libraries, which would impact our build size. Now two things have changed:

1. We are using poetry now, so we can specify optional dev dependencies.
2. VSCode now has an extension for [black](https://marketplace.visualstudio.com/items?itemName=ms-python.black-formatter) and [isort](https://marketplace.visualstudio.com/items?itemName=ms-python.isort). This means that we do not to fangle with any external libraries.

**Comment by irais-valenzuela** [comment]
Related issue: #587

**Comment by LoTerence** [comment]
Note: This docker code from Ida's pr 587, that came from the `main` branch (written by Matt Pereira over a year ago) would enable the python linter:

```
 linter:
    profiles: ["lint"]
    build:  
      context: .
      dockerfile: ./dev/linter.dockerfile
    container_name: linter
    environment:
      - PRE_COMMIT_HOME=${HOME}/.cache/pre-commit
    user: ${UID}:${GID}
    env_file:
      - ./dev/linter.env
    volumes:
      - .:/src:rw
      - ${HOME}/.cache:${HOME}/.cache:rw
```

I need to investigate this further.

- [ ] Test the dev python linter container
- [ ] Upgrade it or make changes if necessary
